### PR TITLE
Add files via upload. Replacing the current spec pdf with the formatted version

### PR DESCRIPTION
**Pull request by camaleon2016**
Adding this to replace the current pdf version.

### CODE REVIEW

**Comment by joshuagl** [comment]
I recommend not including binary files in git, as it is easy for them to become stale and git doesn't handle these kinds of files very well.
Instead, I'd recommend having some GitHub automation which automatically builds the PDF from the markdown file as the spec changes. This generated "release" file can be linked to from the README, if desired, and from the s2c2f website being discussed in #42

**Review by xee5ch — COMMENTED** [review]
I agree with @joshuagl's perspective and recommended steps forward, but will probably need to discuss next steps with the team if you want assistance using Markdown sources, generating PDFs, and releasing built PDF artifacts on the site per these comments and #42.

**Comment by adriandiglio** [comment]
Great suggestions and discussion! As discussed in today's (4/9/2024) S2C2F community call, we agreed about maintaining the spec in markdown, and then configuring automation using GitHub Actions to build it as a PDF. We won't be manually uploading PDFs anymore. Therefore, we are going to close/reject this PR.

**Review by adriandiglio — CHANGES_REQUESTED** [review]
Cancel PR since we won't manually upload PDFs anymore

**Pull request closed without merging**
