### PR TITLE
Delete specification/Secure_Supply_Chain_Consumption_Framework_(S2C2F…

### PR DESCRIPTION
**Pull request by camaleon2016**
…).pdf

This appears to be corrupted and there is another formatted file to take its place.

### CODE REVIEW

**Review by joshuagl — APPROVED** [review]
Per my comment in #44 I think it would be better not to store PDFs in the GitLab repo and instead generate them in a GitHub Action from the Markdown as changes are introduced.

**Comment by joshuagl** [comment]
If the current one is fixed you could tag a release, generate a PDF from it, and link to the static (released) version from anywhere you want folks to reference the non-draft version.

**Comment by adriandiglio** [comment]
Since this PR is just deleting the existing PDF that has issues, let's approve. Futurue PDFs will be generated in an automated fashion

**Review by adriandiglio — APPROVED** [review]
We need to update the README to remove the link to the PDF. We can add it back when we're ready

**Pull request merged**
